---
- assert:
    that:
    - kvm_snapshot_cluster_id is defined

- include_role:
    name: kvm_network
  vars:
    kvm_network_name: "{{ kvm_snapshot_cluster_id }}"
    kvm_network_domain: "{{ kvm_snapshot_cluster_domain }}"

- include_role:
    name: kvm_snapshot_guest
  vars:
    kvm_snapshot_guest_hostnames:
    - master
    - node1
    - node2
