#! ansible-playbook -K
---
- name: Bootstrap the base image
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Pull openshift-ansible from git
    git:
      repo: https://github.com/openshift/openshift-ansible.git
      dest: /tmp/openshift-ansible
