---
- name: Recreate environment
  hosts: localhost
  connection: local
  sudo: yes
  gather_facts: no

  tasks:
  - name: Shutdown existing VMs
    virt:
      name: "{{ item }}"
      state: destroyed
      uri: qemu:///system
    with_items: groups.osev3

  - name: Remove vm logical volumes
    lvol:
      vg: fedora
      lv: "{{ item }}"
      state: absent
      force: yes
    with_items: groups.osev3

  - name: Recreate vm logical volumes
    command: /sbin/lvcreate -s --thinpool fedora/pool00 ansible-base-el7 -n {{ item }}
    with_items: groups.osev3

  - name: Re-launch vms
    virt:
      name: "{{ item }}"
      state: running
      uri: qemu:///system
    with_items: groups.osev3

  - name: Wait for hosts to be available
    wait_for: port=22 host={{ item }}
    with_items: groups.osev3

- name: Bootstrap hosts
  hosts: osev3
  remote_user: root
  become: no
  tags:
  - bootstrap
  tasks:
  - name: Extend lvm volume on vms
    command: lvextend -L +10G -r rhel_base/root
  - copy:
      src: "{{ item }}"
      dest: /etc/yum.repos.d/{{ item }}
    with_items:
    - rhel7.repo
    - rhel7_extras.repo
    - rhel7_ha.repo
    - rhel7_ceph_tools.repo
  - command: yum clean all
  - yum:
      name: libertas-sd8787-firmware-20140804-0.1.git6bce2b0.el7_0.noarch
      state: absent
  - yum:
      name: "*"
      state: latest

  - name: Cleanup cached facts and files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /tmp/ansible/facts
    - /home/jdetiber/.ansible/cp
    - /home/jdetiber/.ansible/tmp
