#! ansible-playbook -K
---
- name: Bootstrap the base image
  hosts: localhost
  connection: local
  become: yes
  vars_prompt:
  - name: kvm_snapshot_cluster_id
    prmopt: Cluster ID
    default: test
  - name: kvm_snapshot_cluster_parent_domain
    prompt: Cluster Parent Domain
    default: example.com
  - name: kvm_snapshot_base_vg
    prompt: Snapshot Base VG
    default: fedora_jdetiber
  tasks:
  - include_role:
      name: kvm_snapshot_cluster
      tasks_from: teardown
