#! ansible-playbook -K
---
- name: Bootstrap the base image
  hosts: localhost
  connection: local
  become: yes
  vars:
    kvm_snapshot_base_os: rhel7
  pre_tasks:
  - assert:
      msg: kvm_snapshot_cluster_id is required
      that:
      - kvm_snapshot_cluster_id is defined
  - assert:
      msg: "kvm_snapshot_base_os is required and must be one of: rhel7,centos7,fedora25"
      that:
      - kvm_snapshot_base_os | default('') in ['rhel7', 'centos7', 'fedora25']
  tasks:
  - include_role:
      name: kvm_snapshot_cluster
      tasks_from: teardown
