#! ansible-playbook -K
---
- name: Stop the snapshot hosts and launch the base image host
  hosts: localhost
  connection: local
  tags: prep
  become: yes
  vars:
    base_host_name: rhel7-base
  gather_facts: no

  tasks:
  - name: Shutdown existing VMs
    virt:
      name: "{{ item }}"
      state: destroyed
      uri: "{{ qemu_uri }}"
    with_items: "{{ groups.all_guests }}"
    failed_when: false

  - name: Remove vm logical volumes
    lvol:
      vg: fedora
      lv: "{{ item }}"
      state: absent
      force: yes
    with_items: "{{ groups.all_guests }}"
    failed_when: false

  - name: launch the base ami
    virt:
      name: "{{ base_host_name }}"
      state: running
      uri: "{{ qemu_uri }}"

  - name: Wait for hosts to be available
    wait_for: port=22 host={{ base_host_name }}.{{ domain_name }}

- name: Update the base host
  hosts: rhel7-base
  tags:
  - update
  tasks:
  - copy:
      src: "{{ item }}"
      dest: /etc/yum.repos.d/{{ item }}
    with_items:
    - rhel7.repo
    - rhel7_extras.repo
  - command: yum clean all
  - yum:
      name: "*"
      state: latest
  - command: yum clean all
  - command: rm -rf /var/log/yum.log
  - pause:
      prompt: Verify the base host is in a good state and survives a reboot before continuing.

- name: Stop the base image host and recreate the snapshot hosts
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  vars:
    base_host_name: rhel7-base
  tags:
  - post
  tasks:
  - name: Stop the base image host
    virt:
      name: "{{ item }}"
      state: destroyed
      uri: "{{ qemu_uri }}"
    with_items: "{{ base_host_name }}"

  - pause: minutes=1

  - name: Recreate vm logical volumes
    command: /sbin/lvcreate -s {{ volume_group }}/{{ base_image }} -n {{ item }}
    with_items: groups.guest_hosts

  - name: Enable the vm logical volumes
    command:  lvchange -ay -K {{ volume_group }}/{{ item }}
    with_items: "{{ groups.guest_hosts }}"

  - name: Re-launch vms
    virt:
      name: "{{ item }}"
      state: running
      uri: "{{ qemu_uri }}"
    with_items: "{{ groups.guest_hosts }}"

  - name: Wait for hosts to be available
    wait_for: port=22 host={{ item }}.{{ domain_name }}
    with_items: "{{ groups.guest_hosts }}"
