---
- name: Check for existence of ssh key
  stat:
    path: /root/.ssh/id_rsa
  register: ssh_key_stat

- name: Create the ssh key if not present
  command: >
    ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ''
  when: not ssh_key_stat.stat.exists

- name: Get list of VMs
  virt:
    command: list_vms
  register: vm_list

- when: kvm_snapshot_base_name not in vm_list.list_vms
  block:
  - name: Ensure the thin pool is present
    lvol:
      lv: "{{ kvm_snapshot_base_thin_pool }}"
      vg: "{{ kvm_snapshot_base_vg }}"
      size: 150G
      state: present
      opts: -T

  - name: Create base lv if needed
    command: >
      lvcreate -T -V25G --thinpool {{ kvm_snapshot_base_thin_pool }}
      -n {{ kvm_snapshot_base_name }} {{ kvm_snapshot_base_vg }}
    when: kvm_snapshot_base_name not in ansible_lvm.lvs.keys()

  - name: Copy the kickstart file
    template:
      src: ks-base-{{ kvm_snapshot_base_os }}-{{ kvm_snapshot_base_arch }}.cfg.j2
      dest: /tmp/ks-base.cfg

  - name: Install the VM
    command: >
      virt-install --name {{ kvm_snapshot_base_name }}
      --vcpus=24 --ram=4096
      --os-type=linux --os-variant={{ 'rhel7' if kvm_snapshot_base_os in ['rhel7', 'centos7'] else kvm_snapshot_base_os }}
      --controller type=scsi,model=virtio-scsi
      --location={{ kvm_snapshot_base_repos[kvm_snapshot_base_os]['netboot'] }}
      --disk path=/dev/{{ kvm_snapshot_base_vg }}/{{ kvm_snapshot_base_name }},cache=none,io=native,discard=unmap,bus=scsi
      --network network=default
      --nographics
      --initrd-inject /tmp/ks-base.cfg
      --extra-args="inst.ks=file:/ks-base.cfg ip=dhcp console=tty0 console=ttyS0,115200n8"
      --wait 20
      --noreboot

  - name: Modify the base image
    command:
      virt-sysprep -d "{{ kvm_snapshot_base_name }}"
      --ssh-inject root:file:/root/.ssh/id_rsa.pub
      --selinux-relabel
