---
- name: Get the list of VMs
  virt:
    command: list_vms
  register: vm_list

- name: Create the VM logical volumes
  command: >
    lvcreate -s {{ kvm_snapshot_base_vg }}/{{ kvm_snapshot_base_name }} -n {{ item }}
  when: item not in ansible_lvm.lvs.keys()
  with_items:
  - "{{ kvm_snapshot_guest_ids }}"

- name: Enable the VM logical volumes
  command: >
    lvchange -ay -K {{ kvm_snapshot_base_vg }}/{{ item }}
  when: item not in ansible_lvm.lvs.keys()
  with_items:
  - "{{ kvm_snapshot_guest_ids }}"

- name: Create the VMs
  command: >
    virt-install --name {{ item }}
    --vcpus={{ kvm_snapshot_guest_vcpus }} --ram={{ kvm_snapshot_guest_ram }}
    --os-type=linux --os-variant={{ 'rhel7' if kvm_snapshot_base_os in ['rhel7', 'centos7'] else kvm_snapshot_base_os }}
    --controller type=scsi,model=virtio-scsi
    --disk path=/dev/{{ kvm_snapshot_base_vg }}/{{ item }},cache=none,io=native,discard=unmap,bus=scsi
    --network network={{ kvm_snapshot_cluster_id }}
    --nographics
    --import
    --noreboot
  when: item not in vm_list.list_vms
  with_items:
  - "{{ kvm_snapshot_guest_ids }}"

- name: Update the VMs
  command: >
    virt-customize -d {{ item.0 }}
    --hostname {{ item.1 }}.{{ kvm_snapshot_cluster_domain }}
    --ssh-inject root:file:/{{ ansible_user_dir }}/.ssh/id_rsa.pub
    --edit /etc/lvm/lvm.conf:'s/issue_discards = 0/issue_discards = 1/'
  when: item.0 not in vm_list.list_vms
  with_together:
  - "{{ kvm_snapshot_guest_ids }}"
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Start the VMs
  virt:
    name: "{{ item }}"
    state: running
  with_items:
  - "{{ kvm_snapshot_guest_ids }}"

- name: Wait for hosts to be available
  wait_for: port=22 host={{ item }}.{{ kvm_snapshot_cluster_domain }}
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Add hosts to proper groups
  add_host:
    name: "{{ item }}.{{ kvm_snapshot_cluster_domain }}"
    groups: bootstrap_hosts
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"
