---
- name: Get the list of VMs
  virt:
    command: list_vms
  register: vm_list

- name: Create the VM logical volumes
  command: >
    lvcreate -s {{ kvm_snapshot_base_vg }}/{{ kvm_snapshot_base_name }} -n {{ item }}
  when: item not in ansible_lvm.lvs.keys()
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Enable the VM logical volumes
  command: >
    lvchange -ay -K {{ kvm_snapshot_base_vg }}/{{ item }}
  when: item not in ansible_lvm.lvs.keys()
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Create the VMs
  command: >
    virt-install --name {{ item }}
    --vcpus=24 --ram=4096
    --os-type=linux --os-variant=rhel7
    --controller type=scsi,model=virtio-scsi
    --disk path=/dev/{{ kvm_snapshot_base_vg }}/{{ item }},cache=none,io=native,discard=unmap,bus=scsi
    --network network={{ kvm_snapshot_cluster_id }}
    --nographics
    --import
    --noreboot
  when: item not in vm_list.list_vms
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Update the VMs
  command: >
    virt-customize -d {{ item }}
    --hostname {{ item }}.{{ kvm_snapshot_cluster_domain }}
  when: item not in vm_list.list_vms
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Start the VMs
  virt:
    name: "{{ item }}"
    state: running
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Wait for hosts to be available
  wait_for: port=22 host={{ item }}.{{ kvm_snapshot_cluster_domain }}
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Add hosts to proper groups
  add_host:
    name: "{{ item }}"
    groups: "{{ kvm_snapshot_guest_group_mappings.master if item.startswith('master') else kvm_snapshot_guest_group_mappings.node }}"
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"
