---
- name: Get the list of VMs
  virt:
    command: list_vms
  register: vm_list

- name: Create the VM logical volumes
  command: >
    lvcreate -s {{ volume_group }}/{{ base_host_name }} -n {{ item }}
  when: item not in ansible_lvm.lvs.keys()
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Enable the VM logical volumes
  command: >
    lvchange -ay -K {{ volume_group }}/{{ item }}
  when: item not in ansible_lvm.lvs.keys()
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Create the VMs
  command: >
    virt-install --name {{ item }}
    --vcpus=24 --ram=4096
    --os-type=linux --os-variant=rhel7
    --controller type=scsi,model=virtio-scsi
    --disk path=/dev/{{ volume_group }}/{{ item }},cache=none,io=native,discard=unmap,bus=scsi
    --network network={{ network.name }}
    --nographics
    --import
    --noreboot
  when: item not in vm_list.list_vms
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Update the VMs
  command: >
    virt-customize -d {{ item }}
    --hostname {{ item }}.{{ domain_name }}
  when: item not in vm_list.list_vms
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Start the VMs
  virt:
    name: "{{ item }}"
    state: running
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"

- name: Wait for hosts to be available
  wait_for: port=22 host={{ item }}.{{ domain_name }}
  with_items:
  - "{{ kvm_snapshot_guest_hostnames }}"
