---
- name: Configure the repos
  template:
    src: host_repos.j2
    dest: /etc/yum.repos.d/rhel7.repo

- name: Enable dnsmasq in NetworkManager
  copy:
    content: |
      [main]
      dns=dnsmasq
    dest: /etc/NetworkManager/conf.d/dnsmasq.conf
  notify: Reload NetworkManager

- name: Configure DNS settings
  copy:
    content: |
      no-negcache
      strict-order
      server=/{{ domain_name }}/192.168.144.1
    dest: /etc/NetworkManager/dnsmasq.d/openshift.conf
  notify: Reload NetworkManager

- when: ansible_architecture == 'ppc64le'
  block:
  - name: Get the state of the smt setting
    command: ppc64_cpu --smt
    register: smt_setting
    changed_when: false

  - name: Turn the smt setting off if needed
    command: ppc64_cpu --smt=off
    when: "'SMT is off' not in smt_setting.stdout"

- name: Ensure libvirt packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ kvm_host_packages + kvm_host_ppc64le_packages if ansible_architecture == 'ppc64le' else kvm_host_packages }}"

- name: Ensure libvirt daemon is started
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Create the libvirt network
  virt_net:
    state: present
    name: "{{ network.name }}"
    xml: "{{ lookup('template', 'templates/libvirt_network.xml.j2') }}"

- name: Set the libvirt network to autostart
  virt_net:
    autostart: yes
    name: "{{ network.name }}"

- name: Start the libvirt network
  virt_net:
    state: active
    name: "{{ network.name }}"
